config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'home#index'
  get 'home/index'

  get 'password_resets/new'
  get 'password_resets/edit'

  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resource :admin, param: :user_id, only: %i[show destroy update]
  resource :director, param: :user_id, only: %i[show update]

  get '/user/existence/:email', to: 'users#email_uniq?', constraints: { email: /.+\..+/}

  namespace :vacancy do
    resources :attributes, param: :attr_id, except: %i[show new]
    resources :country_search, only: %i[index]
    resources :requests, only: %i[index create update]
  end

  namespace :user do
    get '/vacancies', to: 'vacancies#index'
    resource :skill_level, only: %i[edit]
    resource :education, only: %i[edit update]
  end

  resource :manager, param: :user_id, only: %i[show]
  resources :vacancies, param: :vac_id, except: %i[edit]
  resources :users, param: :user_id, except: %i[index new show]
  resources :profiles, param: :user_id, only: %i[show edit update]
  resources :password_resets, only: %i[create edit update]
  resources :account_activations, only: %i[edit]
end

app/controllers/password_resets_controller.rb
# frozen_string_literal: true

class PasswordResetsController < ApplicationController
  before_action :obtain_user, only: %i[edit update]
  before_action :valid_user, only: %i[edit update]
  before_action :check_expiration, only: %i[edit update]

  def create
    @user = User.find_by(email: params[:password_reset][:email].downcase)
    if @user
      @user.create_reset_digest
      @user.send_password_reset_email
      flash[:info] = 'Boom! Password reset instructions have been sent! ;-)'
      redirect_to root_path
    else
      flash.now[:danger] = 'Email address not found'
    end
  end

  def edit; end

  def update
    if params[:user][:password].empty?
      @user.errors.add(:password, "can't be empty")
      render 'edit'
    elsif @user.update_attributes(user_params)
      log_in @user
      flash[:success] = 'Yeah! New password has been set! ;-)'
      redirect_to root_path
    else
      render 'edit'
    end
  end

  private

  def user_params
    params.require(:user).permit(:password, :password_confirmation)
  end

  def obtain_user
    @user = User.find_by(email: params[:email])
  end

  def valid_user
    unless @user&.activated? &&
           @user&.authenticated?(:reset, params[:id])
      redirect_to root_path
    end
  end

  def check_expiration
    return unless @user.password_reset_expired?

    flash[:danger] = 'Password reset has expired.'
    render 'layouts/welcome'
  end
end

app/views/shared/password_reset/_new_pass_set.html.slim
.underlay.fixed-top#passresetlay
.container
.card.card-signin#passresetlayunder.fixed-top
  .card-body
    h5.card-title.text-center Reset password
    = form_for @user, url: password_reset_path(params[:id], html: { class:'form-signin' }) do |f|
      = render 'shared/register_error_messages', object: @user
      = hidden_field_tag :email, @user.email
      .form-label-group
        = f.password_field :password, class: 'form-control', autofocus: true, placeholder: 'Password', required: true
      .form-label-group
        = f.password_field :password_confirmation, class: 'form-control', placeholder: 'Confirm password', required: true
      button.btn.btn-lg.btn-facebook.btn-block.text-uppercase type="submit" Update password