config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'home#index'
  get 'home/index'

  get 'password_resets/new'
  get 'password_resets/edit'

  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resource :admin, param: :user_id, only: %i[show destroy update]
  resource :director, param: :user_id, only: %i[show update]

  get '/user/existence/:email', to: 'users#email_uniq?', constraints: { email: /.+\..+/}

  namespace :vacancy do
    resources :attributes, param: :attr_id, except: %i[show new]
    resources :country_search, only: %i[index]
    resources :requests, only: %i[index create update]
  end

  namespace :user do
    get '/vacancies', to: 'vacancies#index'
    resource :skill_level, only: %i[edit]
    resource :education, only: %i[edit update]
  end

  resource :manager, param: :user_id, only: %i[show]
  resources :vacancies, param: :vac_id, except: %i[edit]
  resources :users, param: :user_id, except: %i[index new show]
  resources :profiles, param: :user_id, only: %i[show edit update]
  resources :password_resets, only: %i[create edit update]
  resources :account_activations, only: %i[edit]
end

app/views/shared/navbar/_navbar.html.slim
/ - if admin?(current_user)
/   = render 'shared/navbar/_admin_navbar'
/ - elsif director?(current_user)
/   = render 'shared/navbar/_director_navbar'
/ - elsif manager?(current_user)
/   = render 'shared/navbar/_manager_navbar'
/ - else

- unless controller_name == "password_resets"
   = render 'shared/navbar/user_navbar'

app/views/shared/navbar/_user_navbar.html.slim
nav.navbar.navbar-expand.navbar-dark.fixed-top.bg-indigo.bg-indigo
  .container
    = link_to image_tag("logo.png", width: "67"), root_path, class: "navbar-brand"
    ul.navbar-nav.ml-auto
      li.nav-item
        = link_to 'Find job', vacancies_path, class: "nav-link"
      li.nav-item.dropdown
        a class="dropdown-toggle nav-link" data-toggle="dropdown"
          | Account
        .dropdown-menu
          - if current_user.admin?
            = link_to 'Admin panel', admin_path, class: "dropdown-item"
          - if current_user.director?
            = link_to 'Director panel', director_path, class: "dropdown-item"
          a
            = link_to 'Profile', profile_path(current_user_profile), class: "dropdown-item"
          - if (current_user.manager?)
            a
              = link_to 'Manager panel', manager_path(current_user), class: "dropdown-item"
            a
              = link_to 'Create vacancy', new_vacancy_path, class: "dropdown-item"
            a
              = link_to 'My vacancies', user_vacancies_path, class: "dropdown-item"
          a
            = link_to 'Vacancy requests', vacancy_requests_path, class: "dropdown-item"
          .dropdown-divider
          = link_to 'Log out', logout_path, method: "delete", class: "dropdown-item"

app/views/shared/navbar/_welcome_navbar.html.slim
nav.navbar.navbar-expand.navbar-dark.fixed-top
  .container
    = link_to image_tag("logo.png", width: "67"), root_path, class: "navbar-brand"
    ul.navbar-nav.ml-auto
      li.nav-item class="nav-link" data-toggle="modal" data-target="#contact-modal-lg" Contact
= render 'shared/home/contact_modal_window'